# Generated by Django 5.2.5 on 2025-08-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assign_to',
            new_name='assigned_to',
        ),
    ]
