# Generated by Django 5.2.5 on 2025-08-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_assign_to_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'TODO'), ('Inprogress', 'IN_PROGRESS'), ('Resolved', 'RESOLVED'), ('Done', 'DONE')], max_length=10),
        ),
    ]
